# Site settings
title: Yaseer Arafat
description: >-
  Software Engineer | .NET Developer | Blogging about CQRS, DDD, and AI
url: "https://emonarafat.github.io" # Your website URL
baseurl: "" # Leave empty if deploying to root

# Author settings
author:
  name: Yaseer Arafat
  email: yaseer.arafat@live.com
  avatar: https://github.com/emonarafat.png
  bio: Passionate about building scalable systems and sharing knowledge.

# Social Links
social:
  github: emonarafat
  linkedin: yaseerarafat
  twitter: emontwitts
  email: yaseer.arafat@live.com

# Navigation links
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Build settings
markdown: kramdown
highlighter: rouge
theme: dev-blog-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Yaseer Arafat
      comments: true
